name: CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  # Cancel the previous builds in the same PR.
  # Allow running concurrently for all non-PR commits.
  group: ci-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.24.x, 1.25.x]
        platform: [ubuntu-latest, windows-latest]
        include:
          # only update test coverage stats with the most recent go version on linux
          - go-version: stable
            platform: ubuntu-latest
            update-coverage: true
            run-diff: true
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v5

      - name: Cache go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Run go fmt
        if: runner.os != 'Windows'
        run: diff -u <(echo -n) <(gofmt -d -s .)

      - name: Ensure go generate produces a zero diff
        if: ${{ matrix.run-diff }}
        shell: bash
        run: go generate -x ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code)

      - name: Run go vet
        run: go vet ./...

      - name: Run go test
        run: go test -v -race -coverprofile coverage.txt -covermode atomic ./...

      - name: Run cmd tests
        run: |
          cd internal/app/dogma
          go test ./...

      - name: Upload coverage to Codecov
        if: ${{ matrix.update-coverage }}
        uses: codecov/codecov-action@v3

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: windows
            goarch: amd64
            ext: .exe
          - goos: linux
            goarch: amd64
            ext: ""
          - goos: linux
            goarch: arm64
            ext: ""
          - goos: darwin
            goarch: amd64
            ext: ""
          - goos: darwin
            goarch: arm64
            ext: ""

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - uses: actions/checkout@v4

      - name: Cache go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Build CLI binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          cd internal/app/dogma
          mkdir -p build
          go build -o build/dogma.${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dogma-${{ matrix.goos }}-${{ matrix.goarch }}
          path: internal/app/dogma/build/dogma.${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}